/**
 * `BrowserBridgeResearchEvent` — the sidecar-LOCAL envelope for entries
 * appended to `~/.browser-bridge-sidecar/research-events.jsonl`. This
 * shape is OBSERVABILITY-ONLY and never crosses the mesh boundary
 * untransformed.
 *
 * ## Why this type exists
 *
 * The sidecar uses `event_id` (random UUID) for local-only debug
 * correlation. Mesh uses `event_ref` (deterministic hash) for distributed
 * UNIQUE. If the sidecar ever POSTs `event_id` to mesh, the two
 * identity schemes collide — mesh would store random UUIDs as if they
 * were stable refs, and dedupe would silently break.
 *
 * The sidecar's `stripEventIdForMeshIngest` (plugin.js) recursively
 * removes the `event_id` field from any mesh-bound payload. This type
 * documents the OPPOSITE direction: the durable local-only shape that
 * `event_id` is allowed in.
 *
 * ## Boundary contract
 *
 *   sidecar local jsonl row  : BrowserBridgeResearchEvent  (has event_id)
 *   mesh observation_events  : ObservationEvent            (has event_ref, no event_id)
 *
 * Convert sidecar→mesh by stripping `event_id` and re-keying on
 * `event_ref`. See `envelope-observation.ts` for the mesh side.
 */
export interface BrowserBridgeResearchEvent {
  /**
   * Random UUID generated by the sidecar at append-time. Local-only
   * correlation key. MUST NOT be POSTed to mesh — there it would
   * collide with mesh's deterministic `event_ref` scheme.
   */
  event_id: string;
  /**
   * Browser research run id (matches a row in the sidecar's
   * research-runs.jsonl spool). FK to the run.
   */
  run_id: string;
  /**
   * Event type within the research-run lifecycle:
   * `dispatched | navigated | ready | answered | failed | monitor_tick`
   * etc. Free-form; consumers should be permissive.
   */
  type: string;
  /** ISO-8601 timestamp the sidecar appended the row. */
  at: string;
  /** Free-form structured detail bag (selectors, response excerpts, errors). */
  details?: Record<string, unknown>;
  /**
   * Optional gateway host label — set by the sidecar from
   * `os.hostname()` when forwarding cross-host events. Not present on
   * pure local rows.
   */
  gateway_host?: string;
}
